# -----------------------------------------------------------------
# STAGE 1: Build the React App
# -----------------------------------------------------------------
FROM node:18-alpine AS builder
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app source code and build
COPY . .
RUN chmod +x ./node_modules/.bin/vite
RUN npm run build

# -----------------------------------------------------------------
# STAGE 2: Serve the App with Nginx
# -----------------------------------------------------------------
FROM nginx:1.25-alpine

# Copy the static build files from the 'builder' stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy our custom Nginx config file over the default one
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the default Nginx port
EXPOSE 80

# The default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]