# Generated by Django 5.1.5 on 2025-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
    ]
